name = "caelestis-frontend"
account_id = "492214885e7a580ccc1d141dfdb4dc5f"
compatibility_date = "2026-08-25"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
preview_urls = false
main = ".svelte-kit/cloudflare/_worker.js"

[[routes]]
pattern = "caelestis.mia.cx"
custom_domain = true

[[services]]
binding = "CAELESTIS_BACKEND"
service = "caelestis-backend"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"
run_worker_first = true
