/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: 6264fb86ea9cde4ed703098a3933c4eb)
interface __BaseEnv_Env {
	BLOBS: R2Bucket;
	DB: D1Database;
	SHARD_STRATEGY: "single";
	SERVER_ID: "01a03930-4f7d-7e72-aa07-666380bf60f7";
	SERVER_NAME: "Caelestis";
	SERVER_DESCRIPTION: "The official Caelestis template server";
	SEASON: "0";
	OPEN_ACCESS: "true";
	BASE_PATH: "/backend";
	TILE_BLOB_GC_MODE: "dry-run";
	USERSCRIPT_BUILD_ID: "development";
	FRONTEND_BUILD_ID: "development";
	TELEMETRY: DurableObjectNamespace<import("./worker").TelemetryShard>;
	ALARM_WATCHER: DurableObjectNamespace<import("./worker").AlarmWatcher>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "TelemetryShard" | "AlarmWatcher";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SHARD_STRATEGY" | "SERVER_ID" | "SERVER_NAME" | "SERVER_DESCRIPTION" | "SEASON" | "OPEN_ACCESS" | "BASE_PATH" | "TILE_BLOB_GC_MODE" | "USERSCRIPT_BUILD_ID" | "FRONTEND_BUILD_ID">> {}
}
