/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: f22ccf8934c5e5410520e4b93841b60e)
interface __BaseEnv_Env {
	BLOBS: R2Bucket;
	DB: D1Database;
	SHARD_STRATEGY: "single";
	SERVER_ID: "00000000-0000-7000-8000-000000000000";
	SERVER_NAME: "Wplace Template Server";
	SERVER_DESCRIPTION: "A self-hosted Wplace template server";
	SEASON: "0";
	OPEN_ACCESS: "false";
	TELEMETRY: DurableObjectNamespace<import("./worker").TelemetryShard>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "TelemetryShard";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SHARD_STRATEGY" | "SERVER_ID" | "SERVER_NAME" | "SERVER_DESCRIPTION" | "SEASON" | "OPEN_ACCESS">> {}
}
