/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: e25a7c23e7a1e54b2c083bb3180b5d05)
interface __BaseEnv_Env {
	BLOBS: R2Bucket;
	DB: D1Database;
	REQUEST_METRICS: AnalyticsEngineDataset;
	SHARD_STRATEGY: "single";
	SERVER_ID: "01a03930-4f7d-7e72-aa07-666380bf60f7";
	SERVER_NAME: "Caelestis";
	SERVER_DESCRIPTION: "The official Caelestis template server";
	SEASON: "0";
	OPEN_ACCESS: "false";
	BASE_PATH: "/backend";
	TILE_BLOB_GC_MODE: "dry-run";
	TELEMETRY: DurableObjectNamespace<import("./worker").TelemetryShard>;
	ALARM_WATCHER: DurableObjectNamespace<import("./worker").AlarmWatcher>;
	STATUS_READ_MODEL: DurableObjectNamespace<import("./worker").StatusReadModelObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "TelemetryShard" | "AlarmWatcher" | "StatusReadModelObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SHARD_STRATEGY" | "SERVER_ID" | "SERVER_NAME" | "SERVER_DESCRIPTION" | "SEASON" | "OPEN_ACCESS" | "BASE_PATH" | "TILE_BLOB_GC_MODE">> {}
}
